# Generated by Django 4.2.6 on 2023-11-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gametype',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='place',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='requiredtime',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='situation',
            name='slug',
        ),
    ]
