# Generated by Django 4.2.6 on 2023-11-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_gametype_slug_remove_place_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameType',
            new_name='game_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='maxHeadcount',
        ),
        migrations.RemoveField(
            model_name='game',
            name='minHeadcount',
        ),
        migrations.RemoveField(
            model_name='game',
            name='requiredTime',
        ),
        migrations.AddField(
            model_name='game',
            name='max_num_ppl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_num_ppl',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='min_time',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='RequiredTime',
        ),
    ]
