# Generated by Django 4.2.6 on 2023-11-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_gametype_game_game_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/games/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='game', to='game.like'),
        ),
    ]
